name: Update Song Recommendation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update_song:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install packages
      run: npm install
    - name: Run script
      env:
        CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
      run: |
        chmod +x update_readme.sh
        .update_readme.sh

    - name: Commit
      uses: actions-x/commit@v6
      with:
        name: ${{ secrets.BOT_NAME }}
        email: ${{ secrets.BOT_EMAIL }}
        files: README.md
        message: Update song recommendation